### ISSUE TITLE
Don't re-implement GitLab API Client

### ISSUE THREAD

**Issue by PurpleBooth** [KainosSoftwareLtd/gov-inspectacle#1]
Other open source projects do this for you, and the less code you need to have the less you need to maintain.

**Comment by Rory80Hz** [comment]
:+1:

**Comment by PurpleBooth** [comment]
I'll try and fix those issues you raised when I get in ☺

On Tue, 3 Nov 2015 13:37 Rory notifications@github.com wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KainosSoftwareLtd/gov-inspectacle/issues/1#issuecomment-153354844
> .
> 
> ## 
> 
> Billie Thompson
> Software Developer
> Purple Booth Ltd

Mob: 07813452516
Web: purplebooth.co.uk
Keybase: http://billie.codes/1NOw29c
LinkedIn: http://billie.codes/1KT8gcI
Twitter: http://billie.codes/1SGPMCw
