### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by PurpleBooth** [KainosSoftwareLtd/gov-inspectacle#11]
- All code produced by the government belongs to "Crown Copyright" not the department.
- License is spelt with an S
- Markdown licenses are a thing and they are a pretty thing
- The year is 2015

**Comment by PurpleBooth** [comment]
Regarding Crown Copyright

> Crown copyright applies "[w]here a work is made by Her Majesty or by an officer or servant of the Crown in the course of his duties".Crown copyright applies "[w]here a work is made by Her Majesty or by an officer or servant of the Crown in the course of his duties".

**Comment by Rory80Hz** [comment]
Fixed by PR, thanks @PurpleBooth
